
import type { Metadata } from "next";
import "./globals.css";
import ThemeInitializer from "../context/ThemeContext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

      </head>
      <body>
        <ThemeInitializer />
        {children}
      </body>
    </html>
  );
}
